### ISSUE TITLE
Errors on deploy 

### ISSUE THREAD

**Issue by RyanBertrand** [convox/action-deploy#10]
Hello, we've been using this action for years and suddenly it stopped working today. Here are the logs from various versions. 

Run convox/action-deploy@v1
```
Deploying
/usr/local/bin/convox: 1: /usr/local/bin/convox: Syntax error: redirection unexpected
```

Run convox/action-deploy@1.1.3
```
Deploying
ERROR: unknown flag: --wait
```

**Comment by nightfury1204** [comment]
@RyanBertrand  use the latest version `convox/action-deploy@2.0.0`

**Comment by nightfury1204** [comment]
@RyanBertrand  also `convox/action-deploy@v1` should work with the `--wait` flag
